version: '3.1'
services:
  nginx:
    image: nginx:1.21
    restart: always
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx-log-data:/var/log/nginx/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d/
      - ./certs:/etc/nginx/certs/
      - /opt/example:/var/www/html/example
volumes:
  nginx-log-data: