version: '2'

services:
  db:
    image: mysql:8.0.31
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
  mysql-data: