version: '2'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
  db-data: